# Site settings
title: Niagara Palestine Coalition
email: niagarapalestine@gmail.com
url: niagarapalestinecoalition.ca
description: "The Niagara Palestine Coalition was founded in the wake of the October crisis in Palestine in 2023 and has members from diverse backgrounds, including Palestinians, Jews, Indigenous peoples from various nations across Turtle Island, academics, union activists, students, youth, and retirees across the Niagara region of Ontario. It has organized weekly demonstrations in Niagara on Sundays as well as fundraisers, educational events, and initiatives that aim to include perspectives from Indigenous communities within its advocacy work for Palestinian rights."
keywords: "Palestine"
skills: "Organize - Mobilize - Free Palestine"
meta_author: Gebril Gabriel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 149954 #80B3FF
  primary-rgb: "20,153,84" #"128,179,255"
  secondary: "000000" #FD6E8A
  secondary-dark: e4312b  #A2122F

# Footer settings
footer:
  copyright: Niagara Palestine Coalition
  location: Location
  social: Socials
  credits: Dedication

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/905palestine
  - title: whatsapp
    url: https://chat.whatsapp.com/KUGkjOWqDOL5UJuFqnrBQ7
  - title: facebook
    url: https://www.facebook.com/905palestine/
  - title: twitter
    url: https://twitter.com/905Palestine
  - title: tiktok
    url: https://www.tiktok.com/@905palestine
  

# Postal address (add as many lines as necessary)
address:
  - line: The 905
  - line: Niagara Region of "Canada"

# Credits content
credits: 'To the only people who speak for Palestine; its children and its resistence.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
